os:
  - linux

language: nix

sudo: required

git:
  depth: 1

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "result/docs/cv.pdf"
    - "result/docs/cv.html"
  skip_cleanup: true
  on:
    tags: true
